### ISSUE TITLE
Plans to adapt Serilog.Sinks.Seq to ASP.NET 5?

### ISSUE THREAD

**Issue by timothy-shields** [serilog/serilog-framework-logging#15]
Are there plans to adapt Serilog.Sinks.Seq to .NET 5 (dnx451+dnxcore50 / dotnet)?  Are there any known difficulties with doing that, or has it just not been a priority?

**Comment by nblumhardt** [comment]
Hi Timothy - absolutely; `dnx451` should work now (just about to check that it is still happy) and `dnxcore50` will be added once Serilog's .NET Core support is finalized. Are you targeting both frameworks currently?

**Comment by timothy-shields** [comment]
`dnx451` works but I need to target both it and `dnxcore50`.

**Comment by jlandersen** [comment]
Hi

Any update on this? Serilog seems to be good with .NET core now, only need Seq :-)

**Comment by nblumhardt** [comment]
On its way - thanks for checking in :-)

Aiming to get something published within a week or so.

**Comment by jlandersen** [comment]
Great stuff! Thanks :+1:

**Comment by nblumhardt** [comment]
https://www.nuget.org/packages/Serilog.Sinks.Seq/2.0.0-beta-23

```json
  "dependencies": {
    "Serilog": "2.0.0-beta-395",
    "Serilog.Sinks.Seq":  "2.0.0-beta-23"
  },
```

Plus:

```csharp
Log.Logger = new LoggerConfiguration()
    .WriteTo.Seq("http://localhost:5341")
    .CreateLogger();

Log.Information("Hello, CoreCLR!");

Log.CloseAndFlush();
```

=

![image](https://cloud.githubusercontent.com/assets/342712/11451659/74075a20-9619-11e5-87ad-088e30722304.png)


Couple of caveats:

* Serilog and the Seq Sink package are both going through stabilisation for .NET Core so expect some more churn, sorry :-)
* The Seq sink package targets DNXCORE50, not the more general DOTNET, because I couldn't get the Serilog package reference working any other way - still figuring this out
* `CloseAndFlush()` on process exit is a good idea on CoreCLR, as there is no `AppDomain` unloading event for the sink to hook into and flush itself (if you're not using `Log`, just `((IDisposable)logger)?.Dispose()` instead

:+1:
