### ISSUE TITLE
Where does Serilog output its logs when following the getting started guide?

### ISSUE THREAD

**Issue by jamesla** [serilog/serilog-framework-logging#22]
I'm testing out serilog in an aspnet5 rc1 final project and having a bit of trouble writing out to the console. However when i fire the web method below nothing appears in the visual studio output window. I must be missing something, anybody know what I am doing wrong?

#startup.cs
````
public Startup(IHostingEnvironment env, IApplicationEnvironment appEnv)
{
    Log.Logger = new LoggerConfiguration().WriteTo.TextWriter(Console.Out).CreateLogger();
}
````

````
public void Configure(IApplicationBuilder app, IHostingEnvironment env, ILoggerFactory loggerFactory)
{
    loggerFactory.AddSerilog();
}
````

#web controller
````
[HttpPost]
public async Task get()
{
    Log.Verbose("hello", new {});
}
````

dependencies section of project.json looks like this
````
    "Microsoft.AspNet.IISPlatformHandler": "1.0.0-rc1-final",
    "Microsoft.AspNet.Mvc": "6.0.0-rc1-final",
    "Microsoft.AspNet.Server.Kestrel": "1.0.0-rc1-final",
    "Microsoft.AspNet.StaticFiles": "1.0.0-rc1-final",
    "Microsoft.Extensions.Configuration.FileProviderExtensions": "1.0.0-rc1-final",
    "Microsoft.Extensions.Configuration.Json": "1.0.0-rc1-final",
    "Microsoft.Extensions.Logging": "1.0.0-rc1-final",
    "Microsoft.AspNet.Authentication.JwtBearer": "1.0.0-rc1-final",
    "Serilog.Framework.Logging": "1.0.0-rc1-final-10071",
    "Microsoft.Extensions.Logging.Console": "1.0.0-rc1-final",
    "Microsoft.Extensions.Logging.Debug": "1.0.0-rc1-final"
````

**Comment by khellang** [comment]
You've specified `Console.Out`. I don't think that is redirected to the Visual Studio output window...

**Comment by jamesla** [comment]
I've set "Redirect All Output Window Text to the Immediate Window" in debug > options. Is there something else I should be doing?

**Comment by nblumhardt** [comment]
May not make a huge difference, but are you running the app under Kestrel or IIS here?

**Comment by jamesla** [comment]
I'm running IIS express.

**Comment by jamesla** [comment]
Anyone?

**Comment by nblumhardt** [comment]
Hi James - since the last Serilog build I think you can use `WriteTo.Console()` in this case. Any more luck with that?

**Comment by nblumhardt** [comment]
Hi again, good news and bad.

1. The package with the fixed Serilog dependency version is up, so `WriteTo.Console()` is now there without extra dependency fiddling to get 2.0-pre installed
2. Your examples miss setting `.MinimumLevel.Verbose()` or similar on the Serilog configuration, so a `.Verbose()` call would be suppressed

But...

1. It doesn't seem like there's any way at all to get console output to the debug window in IIS express

```csharp
Console.WriteLine("Hello, world")
```

doesn't show up in the debug output either.

The example on the README probably needs an update; I was running Kestrel when I first wrote it but the default in VS is IIS Express so that's going to be confusing. Will think about this and fix when I have a better option.

Thanks for the report, I'll close this because I think it's at a dead end but the feedback all-round has been really useful - let us know if you have any more trouble getting up and running.
